/**
 *  All constants should go here
 */

export const LOAD_BOOKS_DATA = 'LOAD_BOOKS_DATA';
export const LOAD_BOOKS_DATA_SUCCESS = 'LOAD_BOOKS_DATA_SUCCESS';
export const LOAD_BOOKS_DATA_ERROR = 'LOAD_BOOKS_DATA_ERROR';
export const BOOKS_SEARCH = 'BOOKS_SEARCH';
export const BOOKS_SEARCH_SUCCESS = 'BOOKS_SEARCH_SUCCESS';
export const BOOKS_SEARCH_ERROR = 'BOOKS_SEARCH_ERROR';
export const LAZY_LOADER_ACTIVATED = 'LAZY_LOADER_ACTIVATED';
export const LAZY_LOADER_ERROR = 'LAZY_LOADER_ERROR';
export const LAZY_LOADER_SUCCESS = 'LAZY_LOADER_SUCCESS';
